export const VENDOR_MAP = {
  microsoft: "Microsoft",
  "amazon web services": "Amazon Web Services",
  aws: "Amazon Web Services",
  google: "Google",
  ibm: "IBM",
  oracle: "Oracle",
  sap: "SAP",
  cisco: "Cisco",
  "dell technologies": "Dell Technologies",
  "hewlett packard enterprise": "Hewlett Packard Enterprise",
  hpe: "Hewlett Packard Enterprise",
  vmware: "VMware",
  broadcom: "Broadcom",
  "red hat": "Red Hat",
  nvidia: "NVIDIA",
  intel: "Intel",
  amd: "AMD",
  apple: "Apple",
  salesforce: "Salesforce",
  servicenow: "ServiceNow",
  adobe: "Adobe",
  atlassian: "Atlassian",
  "palo alto networks": "Palo Alto Networks",
  fortinet: "Fortinet",
  "check point": "Check Point",
  crowdstrike: "CrowdStrike",
  sentinelone: "SentinelOne",
  "trend micro": "Trend Micro",
  sophos: "Sophos",
  kaspersky: "Kaspersky",
  bitdefender: "Bitdefender",
  eset: "ESET",
  proofpoint: "Proofpoint",
  mimecast: "Mimecast",
  barracuda: "Barracuda",
  forcepoint: "Forcepoint",
  zscaler: "Zscaler",
  netskope: "Netskope",
  cloudflare: "Cloudflare",
  akamai: "Akamai",
  splunk: "Splunk",
  elastic: "Elastic",
  rapid7: "Rapid7",
  tenable: "Tenable",
  qualys: "Qualys",
  wiz: "Wiz",
  okta: "Okta",
  cyberark: "CyberArk",
  beyondtrust: "BeyondTrust",
  darktrace: "Darktrace",
  vectra: "Vectra AI",
  armis: "Armis",
  claroty: "Claroty",
  nozomi: "Nozomi Networks",
  dragos: "Dragos",
  recordedfuture: "Recorded Future",
  anomali: "Anomali",
  virustotal: "VirusTotal",
  abuseipdb: "AbuseIPDB",
  crowdsec: "CrowdSec",
  docker: "Docker",
  github: "GitHub",
  gitlab: "GitLab",
  datadog: "Datadog",
  newrelic: "New Relic",
  snowflake: "Snowflake",
  mongodb: "MongoDB",
  redis: "Redis",
  netapp: "NetApp",
  nutanix: "Nutanix",
  veeam: "Veeam",
  rubrik: "Rubrik",
  imperva: "Imperva",
  f5: "F5",
  juniper: "Juniper Networks",
  arista: "Arista Networks"
};
